# Generated by Django 4.2.1 on 2023-05-22 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(auto_created='False', primary_key='True', serialize=False)),
                ('cpm_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(auto_created='False', primary_key='True', serialize=False)),
                ('device_type', models.CharField(blank='True', max_length=100, null='True')),
                ('device_model', models.CharField(blank='True', max_length=100, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(auto_created='False', primary_key='True', serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('company', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='MainApp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Device_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='MainApp.employee')),
                ('assigned_to', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='MainApp.employee')),
                ('device', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='MainApp.device')),
            ],
        ),
    ]
